// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSj38leUsVpTZYD3brLVQXPpEa_RApWzo',
    appId: '1:1009664174679:web:769a821028d06400bc1112',
    messagingSenderId: '1009664174679',
    projectId: 'machine-learning-96ce0',
    authDomain: 'machine-learning-96ce0.firebaseapp.com',
    storageBucket: 'machine-learning-96ce0.firebasestorage.app',
    measurementId: 'G-7LLWH8PDNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHlMm5ceGrkhW8Cix-suxuTgttAeBGmNA',
    appId: '1:1009664174679:android:d3363945006df266bc1112',
    messagingSenderId: '1009664174679',
    projectId: 'machine-learning-96ce0',
    storageBucket: 'machine-learning-96ce0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFYZQp1Zy9AOWdvPtMehkb3JHXeX1OLp8',
    appId: '1:1009664174679:ios:bff627142d98d480bc1112',
    messagingSenderId: '1009664174679',
    projectId: 'machine-learning-96ce0',
    storageBucket: 'machine-learning-96ce0.firebasestorage.app',
    iosBundleId: 'com.example.machineLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFYZQp1Zy9AOWdvPtMehkb3JHXeX1OLp8',
    appId: '1:1009664174679:ios:bff627142d98d480bc1112',
    messagingSenderId: '1009664174679',
    projectId: 'machine-learning-96ce0',
    storageBucket: 'machine-learning-96ce0.firebasestorage.app',
    iosBundleId: 'com.example.machineLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSj38leUsVpTZYD3brLVQXPpEa_RApWzo',
    appId: '1:1009664174679:web:46ab6fce12cbe7edbc1112',
    messagingSenderId: '1009664174679',
    projectId: 'machine-learning-96ce0',
    authDomain: 'machine-learning-96ce0.firebaseapp.com',
    storageBucket: 'machine-learning-96ce0.firebasestorage.app',
    measurementId: 'G-E7QDCNQPC5',
  );
}
